server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_places
    username: postgres
    password: myuser
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  jackson:
    time-zone: Asia/Baku

logging:
  level:
    org.hibernate.SQL: warn
